### ISSUE TITLE
Travis decryption fails on Windows files

### ISSUE THREAD

**Issue by benjcunningham** [benjcunningham/googlecalendar#2]
From failing Travis-CI [Build #1](https://travis-ci.org/benjcunningham/googlecalendar/builds/134298553):

```
0.01s$ openssl aes-256-cbc -K $encrypted_93835e86f9b7_key -iv $encrypted_93835e86f9b7_iv -in tests/testthat/googlecalendar_token.rds.enc -out tests/testthat/googlecalendar_token.rds -d
bad decrypt
140463300056736:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:evp_enc.c:532:

The command "openssl aes-256-cbc -K $encrypted_93835e86f9b7_key -iv $encrypted_93835e86f9b7_iv -in tests/testthat/googlecalendar_token.rds.enc -out tests/testthat/googlecalendar_token.rds -d" failed and exited with 1 during .
```

From [this issue](https://github.com/travis-ci/travis-ci/issues/4746):

> I found the reason for this problem is that the Travis encryption generation variable is different from the Linux system.

So it looks like because I'm using the Ruby client on Windows, the decryption key in the Travis environment isn't matching up. Browsing through the thread, it looks like the present fix is just doing encryption on a different box.

**Comment by benjcunningham** [comment]
Fixed in c793651 by encrypting on a Linux box.

**Comment by houssemzaier** [comment]
so there is no hope with windows right?

**Comment by benjcunningham** [comment]
Unless I've overlooked something, no, it doesn't look like there's a good Windows fix yet. All the same, I rarely need to use `encrypt-file` for this project (only if the token falls off the end of the chain), so I haven't looked into other alternatives recently.
